"""SIM-PRD-VIEW-001 FR-VIEW-12 — auto-generated edit summary strings.

Tiny, deterministic helper. We do not diff JSON structures (the PRD §8 design
decision) — the live artifact payload is a single text blob today. Summaries
are picked from a small set of fixed templates based on who saved the version
and how the save was triggered.
"""
from __future__ import annotations


def for_agent(agent_label: str, cycle_number: int | None = None) -> str:
    if cycle_number:
        return f'Generated by {agent_label} in cycle {cycle_number}'
    return f'Generated by {agent_label}'


def for_user(prior_text: str | None, new_text: str) -> str:
    """Best-effort summary for user edits. Without structured payload we can
    only count whether the body changed and how much."""
    prior = (prior_text or '').strip()
    current = (new_text or '').strip()
    if prior == current:
        return 'You touched the artifact without changing it'
    delta = abs(len(current) - len(prior))
    if delta <= 12:
        return 'You made a small edit'
    if delta <= 120:
        return 'You edited a few lines'
    return 'You rewrote a section'


def for_restore(restored_from_version: int) -> str:
    return f'Restored from version {restored_from_version}'


def for_copilot(field_name: str | None = None) -> str:
    if field_name:
        return f'Co-pilot updated {field_name} at your request'
    return 'Co-pilot edited this artifact at your request'
