"""Add action_items table for GCC v2.0 action queue

Revision ID: ca6c6fda8cdd
Revises: h8i9j0k1l2m3
Create Date: 2026-05-15 23:45:08.871007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6c6fda8cdd'
down_revision = 'h8i9j0k1l2m3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advisor_flags',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('advisor_access_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=True),
    sa.Column('message', sa.String(length=300), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('advisor_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advisor_flags_advisor_access_id'), ['advisor_access_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_advisor_flags_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('contact_activities',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('contact_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=True),
    sa.Column('action_id', sa.String(length=9), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('activity_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pipeline_stage_from', sa.String(length=30), nullable=True),
    sa.Column('pipeline_stage_to', sa.String(length=30), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_activities_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_activities_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('job_title', sa.String(length=200), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('company_size', sa.String(length=50), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('seniority', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_headline', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('twitter_url', sa.String(length=500), nullable=True),
    sa.Column('other_url', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_region', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_action_id', sa.String(length=9), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=9), nullable=True),
    sa.Column('source_notes', sa.String(length=500), nullable=True),
    sa.Column('qualifying_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('pipeline_stage', sa.Enum('prospect', 'active', 'client', 'closed_lost'), nullable=False),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'email', name='uq_contact_email')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_pipeline_stage'), ['pipeline_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_qualifying_score'), ['qualifying_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_user_id'), ['user_id'], unique=False)

    op.create_table('email_campaigns',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=False),
    sa.Column('apollo_sequence_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('contact_count', sa.SmallInteger(), nullable=False),
    sa.Column('sent_count', sa.SmallInteger(), nullable=False),
    sa.Column('reply_count', sa.SmallInteger(), nullable=False),
    sa.Column('bounce_count', sa.SmallInteger(), nullable=False),
    sa.Column('unsubscribe_count', sa.SmallInteger(), nullable=False),
    sa.Column('daily_limit', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_campaigns_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_campaigns_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('layer_income_records',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('layer_number', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('income_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_void', sa.Boolean(), nullable=False),
    sa.Column('voided_by_id', sa.String(length=9), nullable=True),
    sa.Column('recorded_by', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('layer_income_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_layer_income_records_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_mode', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'notification_type', name='uk_np_user_type')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('cta_label', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('published_pages',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=9), nullable=True),
    sa.Column('layer_number', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('published_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_published_pages_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_pages_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_published_pages_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_published_pages_user_id'), ['user_id'], unique=False)

    op.create_table('resume_consents',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('tos_version', sa.String(length=20), nullable=False),
    sa.Column('privacy_version', sa.String(length=20), nullable=False),
    sa.Column('checkbox_1', sa.Boolean(), nullable=False),
    sa.Column('checkbox_2', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('consent_method', sa.String(length=50), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_consents_user_id'), ['user_id'], unique=False)

    op.create_table('signing_documents',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('artifact_version_id', sa.String(length=9), nullable=True),
    sa.Column('layer_number', sa.SmallInteger(), nullable=False),
    sa.Column('pandadoc_document_id', sa.String(length=200), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('document_title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('declined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signing_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signing_documents_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signing_documents_pandadoc_document_id'), ['pandadoc_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signing_documents_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signing_documents_user_id'), ['user_id'], unique=False)

    op.create_table('simulation_chat_messages',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('session_id', sa.String(length=9), nullable=True),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=True),
    sa.Column('action_params', sa.Text(), nullable=True),
    sa.Column('action_status', sa.String(length=20), nullable=True),
    sa.Column('action_result', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('simulation_chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_simulation_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_chat_messages_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_simulation_chat_messages_user_id'), ['user_id'], unique=False)

    op.create_table('user_integrations',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_account_id', sa.String(length=255), nullable=True),
    sa.Column('provider_scope', sa.String(length=100), nullable=True),
    sa.Column('apollo_daily_limit', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_ui_user_provider')
    )
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_integrations_user_id'), ['user_id'], unique=False)

    op.create_table('bundle_type_configs',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('bundle_type', sa.String(length=50), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('sort_order', sa.Text(), nullable=True),
    sa.Column('artifact_categories', sa.Text(), nullable=True),
    sa.Column('include_cover_pdf', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=9), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_type')
    )
    op.create_table('profile_inquiries',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('profile_user_id', sa.String(length=9), nullable=False),
    sa.Column('visitor_name', sa.String(length=100), nullable=False),
    sa.Column('visitor_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('recaptcha_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_inquiries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_inquiries_profile_user_id'), ['profile_user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('bio_generated_at', sa.DateTime(), nullable=True),
    sa.Column('bio_edited', sa.Boolean(), nullable=True),
    sa.Column('avatar_path', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('twitter_url', sa.String(length=255), nullable=True),
    sa.Column('other_link_url', sa.String(length=255), nullable=True),
    sa.Column('other_link_label', sa.String(length=50), nullable=True),
    sa.Column('booking_url', sa.String(length=255), nullable=True),
    sa.Column('booking_btn_label', sa.String(length=50), nullable=True),
    sa.Column('show_contact_form', sa.Boolean(), nullable=True),
    sa.Column('show_booking_btn', sa.Boolean(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('noindex', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_username'), ['username'], unique=True)

    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('artifact_bundles',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=True),
    sa.Column('bundle_type', sa.String(length=50), nullable=False),
    sa.Column('bundle_name', sa.String(length=200), nullable=True),
    sa.Column('audience', sa.String(length=100), nullable=True),
    sa.Column('layer_number', sa.Integer(), nullable=True),
    sa.Column('artifact_ids', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_bundles_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('prefill_corrections',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('prefilled_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=True),
    sa.Column('prefill_source', sa.String(length=100), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prefill_corrections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prefill_corrections_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('simulation_visibility',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('zone_tagline', sa.String(length=200), nullable=True),
    sa.Column('services', sa.JSON(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'limited', 'unavailable', 'hidden', name='sim_availability'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.CHAR(length=9), nullable=False),
    sa.Column('user_id', sa.CHAR(length=9), nullable=False),
    sa.Column('simulation_id', sa.CHAR(length=9), nullable=True),
    sa.Column('star_rating', sa.Integer(), nullable=False),
    sa.Column('layers_attributed', sa.JSON(), nullable=True),
    sa.Column('outcome_text', sa.String(length=300), nullable=False),
    sa.Column('quote_text', sa.String(length=200), nullable=False),
    sa.Column('name_display', sa.Enum('full', 'first_last_initial', 'first_only', 'anonymous'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected'), nullable=False),
    sa.Column('admin_note', sa.String(length=500), nullable=True),
    sa.Column('approved_by', sa.CHAR(length=9), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('expertise_zone_snapshot', sa.String(length=500), nullable=True),
    sa.Column('withdrawn_requested_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('artifact_dependencies',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('upstream_action_id', sa.String(length=9), nullable=True),
    sa.Column('upstream_action_type', sa.String(length=100), nullable=False),
    sa.Column('downstream_action_type', sa.String(length=100), nullable=False),
    sa.Column('fields_passed', sa.Text(), nullable=True),
    sa.Column('upstream_version_used', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_detected_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upstream_action_id'], ['agent_actions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_dependencies_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_dependencies_upstream_action_id'), ['upstream_action_id'], unique=False)

    op.create_table('artifact_versions',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('action_id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('layer_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(length=20), nullable=False),
    sa.Column('edit_summary', sa.String(length=255), nullable=True),
    sa.Column('parent_version_id', sa.String(length=9), nullable=True),
    sa.Column('draft_content', sa.Text(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('draft_updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('prefill_inputs', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('public_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['agent_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_versions_action_id'), ['action_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_versions_simulation_id'), ['simulation_id'], unique=False)

    op.create_table('action_items',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('simulation_id', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.String(length=9), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('urgency_tier', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('layer_number', sa.SmallInteger(), nullable=True),
    sa.Column('action_label', sa.String(length=50), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=False),
    sa.Column('source_action_id', sa.String(length=9), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=9), nullable=True),
    sa.Column('source_contact_id', sa.String(length=9), nullable=True),
    sa.Column('source_income_id', sa.String(length=9), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('is_dismissable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['simulations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_action_id'], ['layer6_action_queue.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.create_index('idx_ai_user_active', ['user_id', 'simulation_id', 'status', 'urgency_tier', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_simulation_id'), ['simulation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('advisor_access', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attribution_opt_out', sa.Boolean(), nullable=False))

    with op.batch_alter_table('advisor_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_shared', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('suggestion_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_urgent', sa.Boolean(), nullable=False))

    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_actions_layer'))

    with op.batch_alter_table('layer6_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer6_configs_simulation_id'))
        batch_op.create_index(batch_op.f('ix_layer6_configs_simulation_id'), ['simulation_id'], unique=True)

    with op.batch_alter_table('layer6_execution_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_tier', sa.String(length=20), nullable=True))

    with op.batch_alter_table('layer6_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer6_outcomes_month'))
        batch_op.create_index(batch_op.f('ix_layer6_outcomes_income_stream_id'), ['income_stream_id'], unique=False)

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_settings_key'))
        batch_op.create_index(batch_op.f('ix_platform_settings_key'), ['key'], unique=True)

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_id', sa.String(length=9), nullable=True))
        batch_op.create_index(batch_op.f('ix_resumes_consent_id'), ['consent_id'], unique=False)
        batch_op.create_foreign_key(None, 'resume_consents', ['consent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pending_email_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pending_email_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recovery_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recovery_token_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('retention_warned_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.drop_column('retention_warned_at')
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('recovery_token_expires')
        batch_op.drop_column('recovery_token')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('pending_email_token_expires')
        batch_op.drop_column('pending_email_token')
        batch_op.drop_column('pending_email')

    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_resumes_consent_id'))
        batch_op.drop_column('consent_id')

    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_settings_key'))
        batch_op.create_index(batch_op.f('ix_platform_settings_key'), ['key'], unique=False)

    with op.batch_alter_table('layer6_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer6_outcomes_income_stream_id'))
        batch_op.create_index(batch_op.f('ix_layer6_outcomes_month'), ['simulation_id', 'reporting_month'], unique=False)

    with op.batch_alter_table('layer6_execution_log', schema=None) as batch_op:
        batch_op.drop_column('model_tier')

    with op.batch_alter_table('layer6_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer6_configs_simulation_id'))
        batch_op.create_index(batch_op.f('ix_layer6_configs_simulation_id'), ['simulation_id'], unique=False)

    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_actions_layer'), ['simulation_id', 'layer_number'], unique=False)

    with op.batch_alter_table('advisor_notes', schema=None) as batch_op:
        batch_op.drop_column('is_urgent')
        batch_op.drop_column('suggestion_type')
        batch_op.drop_column('is_shared')

    with op.batch_alter_table('advisor_access', schema=None) as batch_op:
        batch_op.drop_column('attribution_opt_out')

    with op.batch_alter_table('action_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_action_items_simulation_id'))
        batch_op.drop_index('idx_ai_user_active')

    op.drop_table('action_items')
    with op.batch_alter_table('artifact_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_versions_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_versions_action_id'))

    op.drop_table('artifact_versions')
    with op.batch_alter_table('artifact_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_dependencies_upstream_action_id'))
        batch_op.drop_index(batch_op.f('ix_artifact_dependencies_simulation_id'))

    op.drop_table('artifact_dependencies')
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))

    op.drop_table('user_feedback')
    op.drop_table('simulation_visibility')
    with op.batch_alter_table('prefill_corrections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prefill_corrections_simulation_id'))

    op.drop_table('prefill_corrections')
    with op.batch_alter_table('artifact_bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_bundles_simulation_id'))

    op.drop_table('artifact_bundles')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_jti'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_username'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('profile_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_inquiries_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_inquiries_created_at'))

    op.drop_table('profile_inquiries')
    op.drop_table('bundle_type_configs')
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_integrations_user_id'))

    op.drop_table('user_integrations')
    with op.batch_alter_table('simulation_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_simulation_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_chat_messages_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_simulation_chat_messages_session_id'))

    op.drop_table('simulation_chat_messages')
    with op.batch_alter_table('signing_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signing_documents_user_id'))
        batch_op.drop_index(batch_op.f('ix_signing_documents_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_signing_documents_pandadoc_document_id'))
        batch_op.drop_index(batch_op.f('ix_signing_documents_action_id'))

    op.drop_table('signing_documents')
    with op.batch_alter_table('resume_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_consents_user_id'))

    op.drop_table('resume_consents')
    with op.batch_alter_table('published_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_published_pages_user_id'))
        batch_op.drop_index(batch_op.f('ix_published_pages_slug'))
        batch_op.drop_index(batch_op.f('ix_published_pages_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_published_pages_action_id'))

    op.drop_table('published_pages')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('layer_income_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_layer_income_records_simulation_id'))

    op.drop_table('layer_income_records')
    with op.batch_alter_table('email_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_campaigns_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_email_campaigns_action_id'))

    op.drop_table('email_campaigns')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_user_id'))
        batch_op.drop_index(batch_op.f('ix_contacts_qualifying_score'))
        batch_op.drop_index(batch_op.f('ix_contacts_pipeline_stage'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_name'))

    op.drop_table('contacts')
    with op.batch_alter_table('contact_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_activities_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_contact_activities_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_activities_activity_type'))
        batch_op.drop_index(batch_op.f('ix_contact_activities_action_id'))

    op.drop_table('contact_activities')
    with op.batch_alter_table('advisor_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advisor_flags_simulation_id'))
        batch_op.drop_index(batch_op.f('ix_advisor_flags_advisor_access_id'))

    op.drop_table('advisor_flags')
    # ### end Alembic commands ###
