-- SIM-PRD-CAL-001 -- Layer 1 starter reference data + agent configs
-- Generated by sql/_gen_047.py. Run AFTER 046_calibration.sql.
-- Optional: the schema works with empty tables and nothing calibrates until a
-- dataset has rows, so you can skip this file entirely and upload your own CSV.
--
-- !! THESE FIGURES ARE AN UNVERIFIED STARTER EXTRACT !!
--
-- They are approximate U.S. national BLS OES annual wage percentiles, entered so
-- the Calibration Layer is exercisable the day it deploys. Both datasets load with
-- needs_review = 1, which caps every field calibrated against them at MODERATE
-- confidence no matter how dense the sample -- nothing here can render as
-- "High confidence" to a user.
--
-- Before promoting either dataset (Admin -> Calibration -> Datasets -> "Mark
-- verified"), download the current OES release from
-- https://www.bls.gov/oes/tables.htm and re-upload it as CSV. The upload upserts
-- on cohort, so a verified extract replaces these rows in place.

-- == Dataset 1: annual wages, straight from OES =============================
INSERT INTO reference_datasets
  (id, layer, name, source, source_url, unit, geography_scope,
   credibility_tier, needs_review, derivation_note, as_of_label,
   last_refreshed, refresh_cadence_days, is_active, created_at)
VALUES ('cALdsOES1', 'L1', 'BLS OES National Wages (starter extract)', 'U.S. Bureau of Labor Statistics -- Occupational Employment and Wage Statistics',
  'https://www.bls.gov/oes/tables.htm', 'usd_year', 'national', 'B', 1,
  'Starter extract, unverified. p10/p50/p90 are national annual wage percentiles by SOC occupation. sample_size holds national employment for the occupation, which is the population the OES establishment survey covers -- a data-density signal, not a respondent count. Major-group (##-0000) rows exist so the cohort ladder has a proxy rung when a specific occupation is not held.',
  'May 2024', '2024-05-01', 365, 1, CURRENT_TIMESTAMP);

-- == Dataset 2: independent consulting rate, derived from dataset 1 =========
-- Credibility C on purpose: a modelled transform of wage data, not a rate
-- survey. Tier C can never render High confidence even once verified.
INSERT INTO reference_datasets
  (id, layer, name, source, source_url, unit, geography_scope,
   credibility_tier, needs_review, derivation_note, as_of_label,
   last_refreshed, refresh_cadence_days, is_active, created_at)
VALUES ('cALdsRAT1', 'L1', 'Independent Consulting Rate (derived from BLS OES)', 'Derived from U.S. Bureau of Labor Statistics OES',
  'https://www.bls.gov/oes/tables.htm', 'usd_hour', 'national', 'C', 1,
  'Modelled proxy, not a rate survey. hourly_rate = annual_wage * 1.35 / (2080 * 0.6) -- an employed-equivalent wage grossed up 35% for self-employment tax, benefits and admin, then divided by billable hours at 60% utilisation. Tiered C deliberately: replace with a licensed rate survey when one is available.',
  'May 2024 (derived)', '2024-05-01', 365, 1, CURRENT_TIMESTAMP);

-- == Reference rows: annual wages ===========================================
INSERT INTO reference_data_points
  (id, dataset_id, cohort_json, cohort_hash, p10, p50, p90, mean,
   sample_size, as_of_date, created_at)
VALUES
  ('cOESa0001', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-1111"}', '32061992549ec6691ba4972d855c355c', 52000, 101190, 172380, 106690.0, 1030000, '2024-05-01', CURRENT_TIMESTAMP),  -- Management Analysts
  ('cOESa0002', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-1021"}', 'b350a6ce58c904d089a5430c2d2fb30e', 48000, 101280, 223000, 118390.0, 3500000, '2024-05-01', CURRENT_TIMESTAMP),  -- General and Operations Managers
  ('cOESa0003', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-1151"}', 'eced8cb2e4dbde6039f4ffb131137613', 39000, 65850, 106000, 69175.0, 400000, '2024-05-01', CURRENT_TIMESTAMP),  -- Training and Development Specialists
  ('cOESa0004', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-3131"}', '7746eaf361faed453a907c455c419891', 68000, 127090, 213000, 133795.0, 40000, '2024-05-01', CURRENT_TIMESTAMP),  -- Training and Development Managers
  ('cOESa0005', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "15-1252"}', 'bde8856a1f91006f95f5dd2cdb8501d2', 76000, 133080, 208620, 137695.0, 1650000, '2024-05-01', CURRENT_TIMESTAMP),  -- Software Developers
  ('cOESa0006', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "15-1211"}', 'ad5ae5bf733d41d7da8ab819322ff212', 62000, 103790, 163000, 108145.0, 530000, '2024-05-01', CURRENT_TIMESTAMP),  -- Computer Systems Analysts
  ('cOESa0007', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "15-2051"}', '4015a4c8fc1a251b42bdc8d42e19053c', 63000, 112590, 186000, 118545.0, 200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Data Scientists
  ('cOESa0008', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-1161"}', '1e14288ee5afb81adc874f7a44b40d75', 41000, 76950, 136000, 82725.0, 830000, '2024-05-01', CURRENT_TIMESTAMP),  -- Market Research Analysts and Marketing Specialists
  ('cOESa0009', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-2021"}', '1ec768b17e837325a0b88c3abda65411', 76000, 159660, 239000, 158580.0, 390000, '2024-05-01', CURRENT_TIMESTAMP),  -- Marketing Managers
  ('cOESa0010', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-2051"}', '2fdf512fde0c590729a79992bba06549', 59000, 101910, 185000, 111955.0, 320000, '2024-05-01', CURRENT_TIMESTAMP),  -- Financial and Investment Analysts
  ('cOESa0011', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-3031"}', 'bf4d393c3c67dfa603473a3b133dabbb', 79000, 156100, 239000, 157550.0, 800000, '2024-05-01', CURRENT_TIMESTAMP),  -- Financial Managers
  ('cOESa0012', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "27-1024"}', '0627755dfc63511e7962e398104c134f', 37000, 58910, 98000, 63205.0, 210000, '2024-05-01', CURRENT_TIMESTAMP),  -- Graphic Designers
  ('cOESa0013', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "27-1021"}', '58543b5d9a2c3ef312f9bc0aa076eb67', 44000, 78200, 124000, 81100.0, 30000, '2024-05-01', CURRENT_TIMESTAMP),  -- Commercial and Industrial Designers
  ('cOESa0014', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "41-3091"}', 'be93356cc134dec171167b67e254f99a', 35000, 66600, 135000, 75800.0, 1000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales Representatives of Services, All Other
  ('cOESa0015', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "41-4012"}', '4bea2c6698bc5ab34a474f2e8df1aed8', 38000, 69000, 136000, 78000.0, 1400000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales Representatives, Wholesale and Manufacturing
  ('cOESa0016', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-9111"}', 'a1e743fcb914044365b276ae0c61e6fe', 67000, 110680, 216000, 126090.0, 560000, '2024-05-01', CURRENT_TIMESTAMP),  -- Medical and Health Services Managers
  ('cOESa0017', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "29-1141"}', 'a2306276923cd9f895906613fe2ac35d', 63000, 86070, 132000, 91785.0, 3200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Registered Nurses
  ('cOESa0018', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "25-1099"}', '900eeddd39df951a3a951ee7185d5580', 44000, 78000, 150000, 87500.0, 180000, '2024-05-01', CURRENT_TIMESTAMP),  -- Postsecondary Teachers, All Other
  ('cOESa0019', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "23-1011"}', '8587f5ecfd4b8a29bc5ea396bbb5fcf3', 72000, 145760, 239000, 150630.0, 730000, '2024-05-01', CURRENT_TIMESTAMP),  -- Lawyers
  ('cOESa0020', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "41-9021"}', '9d4a6b45304548dbc953566327bc32fa', 31000, 56620, 114000, 64560.0, 190000, '2024-05-01', CURRENT_TIMESTAMP),  -- Real Estate Sales Agents
  ('cOESa0021', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-1082"}', 'f622005f32ebd325a7d339360c368890', 57000, 100750, 161000, 104875.0, 950000, '2024-05-01', CURRENT_TIMESTAMP),  -- Project Management Specialists
  ('cOESa0022', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-1011"}', '85d47716b072ebb405cd64470c5f2e24', 79000, 206680, 239000, 182840.0, 210000, '2024-05-01', CURRENT_TIMESTAMP),  -- Chief Executives
  ('cOESa0023', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "13-0000"}', '11abff7bd99ab84b6c95f9817588398f', 44000, 79000, 147000, 87250.0, 9500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Business and Financial Operations occupations
  ('cOESa0024', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "11-0000"}', '798bf548e570376c9221d03d47534395', 60000, 116000, 239000, 132750.0, 10500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Management occupations
  ('cOESa0025', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "15-0000"}', '7102bc9cc9f9887f454841a097b8e370', 60000, 104000, 175000, 110750.0, 5000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Computer and Mathematical occupations
  ('cOESa0026', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "27-0000"}', 'e5e70f0b9f2f3c786796c107ac379890', 32000, 61000, 130000, 71000.0, 2200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Arts, Design, Entertainment, Sports and Media occupations
  ('cOESa0027', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "41-0000"}', '92771f301faa5ea0f7ee592fb0b432e4', 26000, 36000, 95000, 48250.0, 13000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales and Related occupations
  ('cOESa0028', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "29-0000"}', 'ad22d5abbc1201d89235e4ff31e6a9c5', 45000, 83000, 175000, 96500.0, 9500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Healthcare Practitioners and Technical occupations
  ('cOESa0029', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "25-0000"}', '3b5fd85a5e19023ce2a778b9ba3f19ae', 36000, 61000, 105000, 65750.0, 9000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Educational Instruction and Library occupations
  ('cOESa0030', 'cALdsOES1', '{"metro": "national", "seniority": "any", "soc_group": "23-0000"}', '47d50d713c3d1d78759bf190f528e684', 50000, 100000, 239000, 122250.0, 1300000, '2024-05-01', CURRENT_TIMESTAMP);  -- Legal occupations

-- == Reference rows: derived hourly consulting rate =========================
INSERT INTO reference_data_points
  (id, dataset_id, cohort_json, cohort_hash, p10, p50, p90, mean,
   sample_size, as_of_date, created_at)
VALUES
  ('cOESh0001', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-1111"}', '32061992549ec6691ba4972d855c355c', 56.25, 109.46, 186.47, 115.41, 1030000, '2024-05-01', CURRENT_TIMESTAMP),  -- Management Analysts
  ('cOESh0002', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-1021"}', 'b350a6ce58c904d089a5430c2d2fb30e', 51.92, 109.56, 241.23, 128.07, 3500000, '2024-05-01', CURRENT_TIMESTAMP),  -- General and Operations Managers
  ('cOESh0003', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-1151"}', 'eced8cb2e4dbde6039f4ffb131137613', 42.19, 71.23, 114.66, 74.83, 400000, '2024-05-01', CURRENT_TIMESTAMP),  -- Training and Development Specialists
  ('cOESh0004', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-3131"}', '7746eaf361faed453a907c455c419891', 73.56, 137.48, 230.41, 144.73, 40000, '2024-05-01', CURRENT_TIMESTAMP),  -- Training and Development Managers
  ('cOESh0005', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "15-1252"}', 'bde8856a1f91006f95f5dd2cdb8501d2', 82.21, 143.96, 225.67, 148.95, 1650000, '2024-05-01', CURRENT_TIMESTAMP),  -- Software Developers
  ('cOESh0006', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "15-1211"}', 'ad5ae5bf733d41d7da8ab819322ff212', 67.07, 112.27, 176.32, 116.98, 530000, '2024-05-01', CURRENT_TIMESTAMP),  -- Computer Systems Analysts
  ('cOESh0007', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "15-2051"}', '4015a4c8fc1a251b42bdc8d42e19053c', 68.15, 121.79, 201.2, 128.23, 200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Data Scientists
  ('cOESh0008', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-1161"}', '1e14288ee5afb81adc874f7a44b40d75', 44.35, 83.24, 147.12, 89.49, 830000, '2024-05-01', CURRENT_TIMESTAMP),  -- Market Research Analysts and Marketing Specialists
  ('cOESh0009', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-2021"}', '1ec768b17e837325a0b88c3abda65411', 82.21, 172.71, 258.53, 171.54, 390000, '2024-05-01', CURRENT_TIMESTAMP),  -- Marketing Managers
  ('cOESh0010', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-2051"}', '2fdf512fde0c590729a79992bba06549', 63.82, 110.24, 200.12, 121.11, 320000, '2024-05-01', CURRENT_TIMESTAMP),  -- Financial and Investment Analysts
  ('cOESh0011', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-3031"}', 'bf4d393c3c67dfa603473a3b133dabbb', 85.46, 168.86, 258.53, 170.43, 800000, '2024-05-01', CURRENT_TIMESTAMP),  -- Financial Managers
  ('cOESh0012', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "27-1024"}', '0627755dfc63511e7962e398104c134f', 40.02, 63.72, 106.01, 68.37, 210000, '2024-05-01', CURRENT_TIMESTAMP),  -- Graphic Designers
  ('cOESh0013', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "27-1021"}', '58543b5d9a2c3ef312f9bc0aa076eb67', 47.6, 84.59, 134.13, 87.73, 30000, '2024-05-01', CURRENT_TIMESTAMP),  -- Commercial and Industrial Designers
  ('cOESh0014', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "41-3091"}', 'be93356cc134dec171167b67e254f99a', 37.86, 72.04, 146.03, 81.99, 1000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales Representatives of Services, All Other
  ('cOESh0015', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "41-4012"}', '4bea2c6698bc5ab34a474f2e8df1aed8', 41.11, 74.64, 147.12, 84.38, 1400000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales Representatives, Wholesale and Manufacturing
  ('cOESh0016', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-9111"}', 'a1e743fcb914044365b276ae0c61e6fe', 72.48, 119.73, 233.65, 136.4, 560000, '2024-05-01', CURRENT_TIMESTAMP),  -- Medical and Health Services Managers
  ('cOESh0017', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "29-1141"}', 'a2306276923cd9f895906613fe2ac35d', 68.15, 93.1, 142.79, 99.28, 3200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Registered Nurses
  ('cOESh0018', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "25-1099"}', '900eeddd39df951a3a951ee7185d5580', 47.6, 84.38, 162.26, 94.66, 180000, '2024-05-01', CURRENT_TIMESTAMP),  -- Postsecondary Teachers, All Other
  ('cOESh0019', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "23-1011"}', '8587f5ecfd4b8a29bc5ea396bbb5fcf3', 77.88, 157.67, 258.53, 162.94, 730000, '2024-05-01', CURRENT_TIMESTAMP),  -- Lawyers
  ('cOESh0020', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "41-9021"}', '9d4a6b45304548dbc953566327bc32fa', 33.53, 61.25, 123.32, 69.84, 190000, '2024-05-01', CURRENT_TIMESTAMP),  -- Real Estate Sales Agents
  ('cOESh0021', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-1082"}', 'f622005f32ebd325a7d339360c368890', 61.66, 108.98, 174.16, 113.44, 950000, '2024-05-01', CURRENT_TIMESTAMP),  -- Project Management Specialists
  ('cOESh0022', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-1011"}', '85d47716b072ebb405cd64470c5f2e24', 85.46, 223.57, 258.53, 197.78, 210000, '2024-05-01', CURRENT_TIMESTAMP),  -- Chief Executives
  ('cOESh0023', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "13-0000"}', '11abff7bd99ab84b6c95f9817588398f', 47.6, 85.46, 159.01, 94.38, 9500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Business and Financial Operations occupations
  ('cOESh0024', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "11-0000"}', '798bf548e570376c9221d03d47534395', 64.9, 125.48, 258.53, 143.6, 10500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Management occupations
  ('cOESh0025', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "15-0000"}', '7102bc9cc9f9887f454841a097b8e370', 64.9, 112.5, 189.3, 119.8, 5000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Computer and Mathematical occupations
  ('cOESh0026', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "27-0000"}', 'e5e70f0b9f2f3c786796c107ac379890', 34.62, 65.99, 140.62, 76.8, 2200000, '2024-05-01', CURRENT_TIMESTAMP),  -- Arts, Design, Entertainment, Sports and Media occupations
  ('cOESh0027', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "41-0000"}', '92771f301faa5ea0f7ee592fb0b432e4', 28.12, 38.94, 102.76, 52.19, 13000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Sales and Related occupations
  ('cOESh0028', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "29-0000"}', 'ad22d5abbc1201d89235e4ff31e6a9c5', 48.68, 89.78, 189.3, 104.39, 9500000, '2024-05-01', CURRENT_TIMESTAMP),  -- Healthcare Practitioners and Technical occupations
  ('cOESh0029', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "25-0000"}', '3b5fd85a5e19023ce2a778b9ba3f19ae', 38.94, 65.99, 113.58, 71.12, 9000000, '2024-05-01', CURRENT_TIMESTAMP),  -- Educational Instruction and Library occupations
  ('cOESh0030', 'cALdsRAT1', '{"metro": "national", "seniority": "any", "soc_group": "23-0000"}', '47d50d713c3d1d78759bf190f528e684', 54.09, 108.17, 258.53, 132.24, 1300000, '2024-05-01', CURRENT_TIMESTAMP);  -- Legal occupations

-- == Agent configs ==========================================================
-- Only fields that can genuinely be bound to the data above are configured. The
-- remaining L1 agents (linkedin_optimization, booking_page, sow_template,
-- agreement_template, referral_network and the outreach agents) emit no
-- calibratable money figure, so they are deliberately absent rather than
-- configured-but-unbound -- an unbound config asks the agent for nothing and would
-- only read as coverage we do not have. Add them from the admin console as you
-- source datasets for speaking fees, project fees and conversion rates.
INSERT INTO calibration_configs
  (id, agent_key, layer, dataset_id, output_field, field_label, unit,
   method, percentiles_json, sigma_model_pct, min_sample_high,
   min_sample_moderate, band_floor_pct, drift_threshold_pct,
   min_reports_to_reweight, is_enabled, created_at)
VALUES
  ('cALcf0001', 'rate_card', 'L1', 'cALdsRAT1', 'billable_hourly_rate', 'Your billable hourly rate', 'usd_hour',
   'bayes_precision', '[10, 50, 90]', 25, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP),  -- The root node every other layer references, so it calibrates first (PRD 11, scheduling).
  ('cALcf0002', 'rate_card', 'L1', 'cALdsOES1', 'projected_annual_income', 'Projected annual income at this rate', 'usd_year',
   'bayes_precision', '[10, 50, 90]', 30, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP),  -- Wider model sigma than the rate itself: an annual projection compounds utilisation assumptions.
  ('cALcf0003', 'consulting_proposal', 'L1', 'cALdsRAT1', 'blended_hourly_rate', 'Blended hourly rate on this proposal', 'usd_hour',
   'bayes_precision', '[10, 50, 90]', 25, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP),
  ('cALcf0004', 'negotiation_script', 'L1', 'cALdsOES1', 'target_annual_compensation', 'Target annual compensation', 'usd_year',
   'bayes_precision', '[10, 50, 90]', 20, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP),  -- Tighter sigma: the target is the user stated intent, so market data should not override it as hard.
  ('cALcf0005', 'role_search', 'L1', 'cALdsOES1', 'annualised_engagement_value', 'Annualised value of these engagements', 'usd_year',
   'bayes_precision', '[10, 50, 90]', 35, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP);  -- Widest sigma in L1: fractional engagement value is the least comparable to an employed wage.
