"""Generator for sql/047_calibration_seed_l1.sql (SIM-PRD-CAL-001).

Kept in the repo so the seed can be regenerated after editing the occupation
table, and so the cohort hashes are never hand-typed. Run from the repo root:
    python sql/_gen_047.py
"""
import hashlib
import json


def cohort(soc, metro='national', sen='any'):
    return {'soc_group': soc, 'metro': metro, 'seniority': sen}


def chash(soc):
    blob = json.dumps(cohort(soc), sort_keys=True, separators=(',', ':'))
    return hashlib.md5(blob.encode('utf-8')).hexdigest()


def cjson(soc):
    return json.dumps(cohort(soc), sort_keys=True)


# soc, title, p10, p50, p90, national employment
DETAILED = [
    ('13-1111', 'Management Analysts', 52000, 101190, 172380, 1030000),
    ('11-1021', 'General and Operations Managers', 48000, 101280, 223000, 3500000),
    ('13-1151', 'Training and Development Specialists', 39000, 65850, 106000, 400000),
    ('11-3131', 'Training and Development Managers', 68000, 127090, 213000, 40000),
    ('15-1252', 'Software Developers', 76000, 133080, 208620, 1650000),
    ('15-1211', 'Computer Systems Analysts', 62000, 103790, 163000, 530000),
    ('15-2051', 'Data Scientists', 63000, 112590, 186000, 200000),
    ('13-1161', 'Market Research Analysts and Marketing Specialists', 41000, 76950, 136000, 830000),
    ('11-2021', 'Marketing Managers', 76000, 159660, 239000, 390000),
    ('13-2051', 'Financial and Investment Analysts', 59000, 101910, 185000, 320000),
    ('11-3031', 'Financial Managers', 79000, 156100, 239000, 800000),
    ('27-1024', 'Graphic Designers', 37000, 58910, 98000, 210000),
    ('27-1021', 'Commercial and Industrial Designers', 44000, 78200, 124000, 30000),
    ('41-3091', 'Sales Representatives of Services, All Other', 35000, 66600, 135000, 1000000),
    ('41-4012', 'Sales Representatives, Wholesale and Manufacturing', 38000, 69000, 136000, 1400000),
    ('11-9111', 'Medical and Health Services Managers', 67000, 110680, 216000, 560000),
    ('29-1141', 'Registered Nurses', 63000, 86070, 132000, 3200000),
    ('25-1099', 'Postsecondary Teachers, All Other', 44000, 78000, 150000, 180000),
    ('23-1011', 'Lawyers', 72000, 145760, 239000, 730000),
    ('41-9021', 'Real Estate Sales Agents', 31000, 56620, 114000, 190000),
    ('13-1082', 'Project Management Specialists', 57000, 100750, 161000, 950000),
    ('11-1011', 'Chief Executives', 79000, 206680, 239000, 210000),
]

# Major groups exist so the cohort ladder always has a proxy rung to land on.
MAJOR = [
    ('13-0000', 'Business and Financial Operations occupations', 44000, 79000, 147000, 9500000),
    ('11-0000', 'Management occupations', 60000, 116000, 239000, 10500000),
    ('15-0000', 'Computer and Mathematical occupations', 60000, 104000, 175000, 5000000),
    ('27-0000', 'Arts, Design, Entertainment, Sports and Media occupations', 32000, 61000, 130000, 2200000),
    ('41-0000', 'Sales and Related occupations', 26000, 36000, 95000, 13000000),
    ('29-0000', 'Healthcare Practitioners and Technical occupations', 45000, 83000, 175000, 9500000),
    ('25-0000', 'Educational Instruction and Library occupations', 36000, 61000, 105000, 9000000),
    ('23-0000', 'Legal occupations', 50000, 100000, 239000, 1300000),
]
ALL_ROWS = DETAILED + MAJOR

DS_ANNUAL = 'cALdsOES1'
DS_RATE = 'cALdsRAT1'
AS_OF = '2024-05-01'

UTILISATION = 0.60
OVERHEAD = 1.35
YEAR_HOURS = 2080
RATE_FACTOR = OVERHEAD / (YEAR_HOURS * UTILISATION)

# id, agent_key, dataset, output_field, label, unit, sigma_model_pct, note
CONFIGS = [
    ('cALcf0001', 'rate_card', DS_RATE, 'billable_hourly_rate',
     'Your billable hourly rate', 'usd_hour', 25,
     'The root node every other layer references, so it calibrates first (PRD 11, scheduling).'),
    ('cALcf0002', 'rate_card', DS_ANNUAL, 'projected_annual_income',
     'Projected annual income at this rate', 'usd_year', 30,
     'Wider model sigma than the rate itself: an annual projection compounds utilisation assumptions.'),
    ('cALcf0003', 'consulting_proposal', DS_RATE, 'blended_hourly_rate',
     'Blended hourly rate on this proposal', 'usd_hour', 25, None),
    ('cALcf0004', 'negotiation_script', DS_ANNUAL, 'target_annual_compensation',
     'Target annual compensation', 'usd_year', 20,
     'Tighter sigma: the target is the user stated intent, so market data should not override it as hard.'),
    ('cALcf0005', 'role_search', DS_ANNUAL, 'annualised_engagement_value',
     'Annualised value of these engagements', 'usd_year', 35,
     'Widest sigma in L1: fractional engagement value is the least comparable to an employed wage.'),
]

HEADER = """-- SIM-PRD-CAL-001 -- Layer 1 starter reference data + agent configs
-- Generated by sql/_gen_047.py. Run AFTER 046_calibration.sql.
-- Optional: the schema works with empty tables and nothing calibrates until a
-- dataset has rows, so you can skip this file entirely and upload your own CSV.
--
-- !! THESE FIGURES ARE AN UNVERIFIED STARTER EXTRACT !!
--
-- They are approximate U.S. national BLS OES annual wage percentiles, entered so
-- the Calibration Layer is exercisable the day it deploys. Both datasets load with
-- needs_review = 1, which caps every field calibrated against them at MODERATE
-- confidence no matter how dense the sample -- nothing here can render as
-- "High confidence" to a user.
--
-- Before promoting either dataset (Admin -> Calibration -> Datasets -> "Mark
-- verified"), download the current OES release from
-- https://www.bls.gov/oes/tables.htm and re-upload it as CSV. The upload upserts
-- on cohort, so a verified extract replaces these rows in place.
"""

ANNUAL_NOTE = (
    'Starter extract, unverified. p10/p50/p90 are national annual wage percentiles '
    'by SOC occupation. sample_size holds national employment for the occupation, '
    'which is the population the OES establishment survey covers -- a data-density '
    'signal, not a respondent count. Major-group (##-0000) rows exist so the cohort '
    'ladder has a proxy rung when a specific occupation is not held.'
)

RATE_NOTE = (
    'Modelled proxy, not a rate survey. hourly_rate = annual_wage * {overhead} / '
    '({hours} * {util}) -- an employed-equivalent wage grossed up {gross:.0f}% for '
    'self-employment tax, benefits and admin, then divided by billable hours at '
    '{utilpct:.0f}% utilisation. Tiered C deliberately: replace with a licensed rate '
    'survey when one is available.'
).format(overhead=OVERHEAD, hours=YEAR_HOURS, util=UTILISATION,
         gross=(OVERHEAD - 1) * 100, utilpct=UTILISATION * 100)

CONFIG_PREAMBLE = """-- == Agent configs ==========================================================
-- Only fields that can genuinely be bound to the data above are configured. The
-- remaining L1 agents (linkedin_optimization, booking_page, sow_template,
-- agreement_template, referral_network and the outreach agents) emit no
-- calibratable money figure, so they are deliberately absent rather than
-- configured-but-unbound -- an unbound config asks the agent for nothing and would
-- only read as coverage we do not have. Add them from the admin console as you
-- source datasets for speaking fees, project fees and conversion rates."""


def sq(text):
    """Escape a SQL single-quoted literal."""
    return text.replace("'", "''")


def dataset_insert(ds_id, name, source, unit, tier, note, as_of_label):
    return (
        "INSERT INTO reference_datasets\n"
        "  (id, layer, name, source, source_url, unit, geography_scope,\n"
        "   credibility_tier, needs_review, derivation_note, as_of_label,\n"
        "   last_refreshed, refresh_cadence_days, is_active, created_at)\n"
        "VALUES ('{id}', 'L1', '{name}', '{source}',\n"
        "  'https://www.bls.gov/oes/tables.htm', '{unit}', 'national', '{tier}', 1,\n"
        "  '{note}',\n"
        "  '{as_of_label}', '{as_of}', 365, 1, CURRENT_TIMESTAMP);"
    ).format(id=ds_id, name=sq(name), source=sq(source), unit=unit, tier=tier,
             note=sq(note), as_of_label=sq(as_of_label), as_of=AS_OF)


def _join_values(rows):
    """Join (sql, trailing_comment) pairs into a VALUES list.

    The separator must land on the SQL, before the comment — a comma placed after
    a `--` comment is itself commented out, which silently truncates the INSERT.
    """
    out = []
    for i, (sql, comment) in enumerate(rows):
        sep = ',' if i < len(rows) - 1 else ';'
        out.append(sql + sep + ('  -- ' + comment if comment else ''))
    return '\n'.join(out)


def point_rows(prefix, dataset_id, transform):
    rows = []
    for i, (soc, title, p10, p50, p90, emp) in enumerate(ALL_ROWS, start=1):
        v10, v50, v90 = (transform(p10), transform(p50), transform(p90))
        mean = round((v10 + v50 + v50 + v90) / 4.0, 2)
        rows.append((
            "  ('{id}', '{ds}', '{cj}', '{ch}', {p10}, {p50}, {p90}, {mean}, {n}, '{ao}', CURRENT_TIMESTAMP)".format(
                id='{}{:04d}'.format(prefix, i), ds=dataset_id, cj=sq(cjson(soc)),
                ch=chash(soc), p10=v10, p50=v50, p90=v90, mean=mean, n=emp, ao=AS_OF),
            title,
        ))
    return (
        "INSERT INTO reference_data_points\n"
        "  (id, dataset_id, cohort_json, cohort_hash, p10, p50, p90, mean,\n"
        "   sample_size, as_of_date, created_at)\nVALUES\n" + _join_values(rows)
    )


def config_rows():
    rows = []
    for cid, agent, ds, field, label, unit, sigma, note in CONFIGS:
        rows.append((
            ("  ('{id}', '{agent}', 'L1', '{ds}', '{field}', '{label}', '{unit}',\n"
             "   'bayes_precision', '[10, 50, 90]', {sigma}, 300, 40, 8.00, 15.00, 30, 1, CURRENT_TIMESTAMP)"
             ).format(id=cid, agent=agent, ds=ds, field=field, label=sq(label),
                      unit=unit, sigma=sigma),
            note,
        ))
    return (
        "INSERT INTO calibration_configs\n"
        "  (id, agent_key, layer, dataset_id, output_field, field_label, unit,\n"
        "   method, percentiles_json, sigma_model_pct, min_sample_high,\n"
        "   min_sample_moderate, band_floor_pct, drift_threshold_pct,\n"
        "   min_reports_to_reweight, is_enabled, created_at)\nVALUES\n" + _join_values(rows)
    )


def main():
    parts = [
        HEADER,
        '-- == Dataset 1: annual wages, straight from OES =============================',
        dataset_insert(DS_ANNUAL, 'BLS OES National Wages (starter extract)',
                       'U.S. Bureau of Labor Statistics -- Occupational Employment '
                       'and Wage Statistics',
                       'usd_year', 'B', ANNUAL_NOTE, 'May 2024'),
        '',
        '-- == Dataset 2: independent consulting rate, derived from dataset 1 =========',
        '-- Credibility C on purpose: a modelled transform of wage data, not a rate',
        '-- survey. Tier C can never render High confidence even once verified.',
        dataset_insert(DS_RATE, 'Independent Consulting Rate (derived from BLS OES)',
                       'Derived from U.S. Bureau of Labor Statistics OES',
                       'usd_hour', 'C', RATE_NOTE, 'May 2024 (derived)'),
        '',
        '-- == Reference rows: annual wages ===========================================',
        point_rows('cOESa', DS_ANNUAL, lambda v: v),
        '',
        '-- == Reference rows: derived hourly consulting rate =========================',
        point_rows('cOESh', DS_RATE, lambda v: round(v * RATE_FACTOR, 2)),
        '',
        CONFIG_PREAMBLE,
        config_rows(),
        '',
    ]
    out = '\n'.join(parts)
    with open('sql/047_calibration_seed_l1.sql', 'w', encoding='utf-8') as fh:
        fh.write(out)
    print('wrote sql/047_calibration_seed_l1.sql — {} occupations, {} configs'.format(
        len(ALL_ROWS), len(CONFIGS)))
    print('rate factor {:.8f}  (p50 101190 -> {:.2f}/hr)'.format(
        RATE_FACTOR, 101190 * RATE_FACTOR))


if __name__ == '__main__':
    main()
